Get Set , Load User Cache
PonderTeam/ponder-app pull request #118
Opened 2024-04-07 12:07 UTC by JeremyLin003

fixes #102 

When getting user or study set for the first time, stores the object as a string (JSON) in session storage
I haven't tested the ones that call firebase
uid is also stored under key "userId" to allow for easy access of user info without needing to pass uid between every page

2024-04-07 18:26 UTC, ashkjones requested changes
Please fix how the user is saved locally when using the firestore. I can help you set up the local emulator if you need me to.

Great work though!!

2024-04-07 18:26 UTC, ashkjones commented on src/app/services/user-info-firebase.service.ts
> +          ))
This doesn't appear to be saving the owned and viewed study sets of the user. 

Console log showing that the correct user data was fetched from the firestore, but empty arrays being created
<img width="1462" alt="image" src="https://github.com/PonderTeam/ponder-app/assets/4361319/e79188fb-fc4c-4847-886c-8c0169d49594">

On user cache hit after page reload, we get an empty page
<img width="1458" alt="image" src="https://github.com/PonderTeam/ponder-app/assets/4361319/2d5a385e-5798-4065-8d8b-81e5dced4bcc">

2024-04-08 06:35 UTC, B-Yamawaki commented on src/app/services/user-info-fake.service.ts
> +    if (id === sessionStorage.getItem("userId")) {
Could you change this to checking if the actual user has been created. `if (sessionStorage.getItem(id))` It doesn't change too much, but it helps make things easier for the sign in implementation. And the same in the firebase service.

2024-04-08 06:39 UTC, B-Yamawaki commented on src/app/services/user-info-fake.service.ts
> +    if (id === sessionStorage.getItem("userId")) {
You also don't have to set userId, as I can do that upon sign in.

2024-04-08 15:56 UTC, merged