Clear, Check, Show Answer Sequences
PonderTeam/ponder-app pull request #122
Opened 2024-04-07 20:33 UTC by iamdylanhuynh001

# Fixes #45, Fixes #46, and Fixes #47 

## Created a button that shows sequence answers
- The sequence sidebar is populated with the correct sequence answer.  
- Cardpool card visibility updated to match the sequence sidebar 
## Created a button that clears the user's sequence in the sequence sidebar
- Removes all the cards in the sequence sidebar
- Refreshes the cardpool
## Created a button that checks the sequence of answers
- Iterate through the user's sequence and check sequence
- Pop up dialog if the user's sequence is correct or incorrect

2024-04-07 23:28 UTC, B-Yamawaki requested changes
You did great on the logic parts. There are a few styling things that have to be done.

2024-04-07 23:28 UTC, B-Yamawaki commented on src/app/check-pop-up/check-pop-up.component.html
> +<mat-dialog-actions>
could you get rid of this close button and just have it display the text. If you wanted to keep an indicator of closing you could try to add an X at the top right, but I don't think it is necessary.

2024-04-07 23:28 UTC, B-Yamawaki commented on src/app/check-pop-up/check-pop-up.component.html
> +<h2 mat-dialog-title>{{data?.answer}}</h2>
Based on the result of the answer, could you have the color of the pop up be green or red. You can pass styling specifications inside of the html so you can style based on conditions I think.

2024-04-07 23:28 UTC, B-Yamawaki commented on src/app/study-sequence/study-sequence.component.html
>      <div class="check-show-answer">
Can you space these buttons out more. This can be done by putting them in a grid or flex and designating the gap attribute.

2024-04-07 23:28 UTC, B-Yamawaki commented on src/app/study-sequence/study-sequence.component.scss
>  .sequence-select {
Can you apply the background colors to this and the check-show-answer classes. You should create a new file called _study-sequence-theme.scss and apply theme stylings in there. This is where you do the mixin things, and don't forget to add it to the global style sheet. To differentiate the sequence select menu and the background, you can outline the "select-title" class.

2024-04-09 05:27 UTC, iamdylanhuynh001 commented
I believe I fixed all revisions

2024-04-09 07:51 UTC, B-Yamawaki approved these changes
Looks good. Note I made one more change to add the colors to the select sequence area.

2024-04-09 07:51 UTC, merged