116 update user sets
PonderTeam/ponder-app pull request #127
Opened 2024-04-09 13:34 UTC by JeremyLin003

fixes #116 

Theoretically this should update user's recent and owned lists when viewing a set.
After editing a set, the user is sent back to view page, so it'll update there.

json server: all sets belong to "user1" so owned sets will not update without tweaks (edit json, session storage, etc)

firebase save user doesn't work without the subscribe statement, I can look into it in the future.

2024-04-09 16:31 UTC, ashkjones commented on src/app/services/user-info-firebase.service.ts
> +      })
This occurs due to the lazy nature of observables. They won't complete unless there is a subscriber that consumes the observable's output. I suggest moving the subscribe out of saveUser and into updateViewDate like so
``` ts
  override updateViewDate(studySet: StudySetData){
    this.loadUser(sessionStorage.getItem("uid")!)
    .pipe(take(1)).subscribe(user =>{
      user.updateRecentSets({setId: studySet.id! , viewed: new Date()});
      if(studySet.owner){
        if (studySet.owner === sessionStorage.getItem("uid")){
        user.updateOwned({setId: studySet.id! , viewed: new Date()});
        }
      }
      this.saveUser(user).subscribe();
    })
  }
```

2024-04-09 16:33 UTC, ashkjones commented on src/app/services/user-info-firebase.service.ts
> +  override updateViewDate(studySet: StudySetData){
Please add a space before the opening curly brace "{". 
```ts
override updateViewDate(studySet: StudySetData) {
```
Fix this everywhere in your code

2024-04-09 16:36 UTC, ashkjones commented on src/app/edit-create-study-set/edit-create-study-set.component.ts
> +  @Input() userId: string = sessionStorage.getItem("uid")!; // remove later
remove the "remove later" comment because this is probably the finalized version of this code 😄

2024-04-11 06:47 UTC, B-Yamawaki commented on src/environments/environment.development.ts
> +  useFirebase: true,  // change to switch between json server or firebase
I would change this to false before merging it

2024-04-11 08:51 UTC, B-Yamawaki requested changes
When I created a new set and pressed done, the home page shows this because it created a recentset entry without any sid, and the sessionStorage stored two versions of the same set with different IDs. 

I believe these problems stem from the same issue. In the study set dev service, the saveSet method creates an observable, subscribes to the observable in the method, then returns the observable where it is subscribed to again in the edit/create component. Subscribing at those two times does not produce the same result. It actually makes two separate db calls. The observable is kind of like a portable block of code that whenever you subscribe to it, it runs. I would not subscribe to the observable in the method and instead use a map to do all of the side effects and return value of the method. If you need clarification let me know. 

After further review, another issue is that for a new set, the generated id is never assigned to the study set. This can be done as one of the side effects in the save method.

I think this is more related to the previous task of the caching, but it wasn't caught because newly created sets would not appear on the home page and this is a problem with only newly created sets. Since the homepage gets updated now, it was easier to find this bug.

Thank you for your hard work. The updating of the recent and owned sets looks good beyond the problem that this feature helped to reveal. 

![image](https://github.com/PonderTeam/ponder-app/assets/80545567/b20daf18-8254-4a14-96fa-9f9fb99f776a)

2024-04-12 00:51 UTC, ashkjones approved these changes

2024-04-12 08:00 UTC, B-Yamawaki approved these changes
Great job

2024-04-12 08:00 UTC, merged