36 search card sequence editor
PonderTeam/ponder-app pull request #131
Opened 2024-04-12 03:04 UTC by euilee0129

#36 fixes
Search bar
- utilized pipe called filter, filters search based on words searched in bar
- border get darkened, changes color to signify search bar is clicked and being used

2024-04-12 03:23 UTC, ashkjones requested changes
Good start. I am requesting some code style changes and that you use colors from the theme

2024-04-12 03:23 UTC, ashkjones commented on src/app/sequence-editor/_sequence-editor-theme.scss
> +  }
Could you combine the #search-bar and .card-search-bar styles like I asked on discord?

2024-04-12 03:23 UTC, ashkjones commented on src/app/sequence-editor/_sequence-editor-theme.scss
> +    background-color: #dcefc7;
I don't think the color is distinctive enough. Also, use a color from the theme, not a hard coded color.

<img width="346" alt="image" src="https://github.com/PonderTeam/ponder-app/assets/4361319/c1125772-f31c-4b2b-8619-0e6df2583e44">

2024-04-12 03:30 UTC, ashkjones requested changes

2024-04-12 03:30 UTC, ashkjones commented on src/app/sequence-editor/sequence-editor.component.html
> +        @for( flashcard of filteredCards; track filteredCards){
Try to keep line lengths under 100 characters. You can check in the bottom right of vs code
<img width="495" alt="image" src="https://github.com/PonderTeam/ponder-app/assets/4361319/9edceea8-1c68-4db3-b4e2-03ff9159d0bc">

2024-04-12 03:30 UTC, ashkjones commented on src/app/sequence-editor/sequence-editor.component.ts
> +    this.filteredCards = this.flashcards.filter(item => item.term.toLowerCase().includes(filterValue.toLowerCase()));
Try to keep line lengths under 100 characters

2024-04-12 03:30 UTC, ashkjones commented on src/app/filter.pipe.spec.ts
I don't think you ever use this

2024-04-12 03:30 UTC, ashkjones commented on src/app/filter.pipe.ts
i don't think you use this file either

2024-04-12 03:30 UTC, ashkjones commented on src/app/sequence-editor/sequence-editor.component.ts
> +        FilterPipe
remove the filter pip because it isn't used

2024-04-14 19:23 UTC, iamdylanhuynh001 approved these changes
Search bar searches correctly.

Seems good to me

2024-04-14 19:25 UTC, ashkjones approved these changes

2024-04-14 19:25 UTC, merged