Isolated Edit-Create Parent
PonderTeam/ponder-app pull request #69
Opened 2024-03-05 04:31 UTC by JeremyLin003

Fixes #57 

- Created Edit Create parent component
- Placed visual placeholders to emulate final design
- Added minimal routing to navigate to Edit Create page from NavBar
- I will be updating the visuals and functionality of this page further in #20  
 
![image](https://github.com/PonderTeam/ponder-app/assets/80878588/880785a7-38e8-4466-b1fc-8a0cb78add00)

2024-03-05 21:36 UTC, ashkjones requested changes
I requesting some code be added to components. When you implement the tabs on your next PR, please make sure to make them a component so they can be reused on the view pages as well.

2024-03-05 21:36 UTC, ashkjones commented on src/app/edit-create-study-set/edit-create-study-set.component.html
> +      <p class = "page-title">Create Study Set</p>
change `p` to `h1` and set a global style in `src/app/styles.scss` for all headings `h1`.

2024-03-05 21:36 UTC, ashkjones commented on src/app/edit-create-study-set/edit-create-study-set.component.scss
> +  }
make this the global style for `h1` in the `src/styles.scss` file. In `styles.scss` add:
```css
h1 {
  font: mat.get-theme-typography(theme.$ponder-light-theme, headline-large);
  line-height:0em;
}
```

2024-03-10 21:14 UTC, B-Yamawaki approved these changes
Good Job

2024-03-10 21:17 UTC, merged